num1 = int(input("enter first number : "))
num2 = int(input("enter second number: "))
print ("addition", num1 + num2)
print ("subtraction", num1 - num2)
print ("multiplication", num1 * num2)
print ("division", num1 / num2)
print ("divison without remainder", num1 // num2)
print ("remainder", num1 % num2)
print ("power", num1 ** num2)